# Generated by Django 4.2.5 on 2023-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('dueDate', models.DateField()),
                ('taskDescription', models.TextField(max_length=250)),
            ],
        ),
    ]
