# Generated by Django 4.2.5 on 2023-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskPriority',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
