# Generated by Django 4.2.5 on 2023-12-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
