# Generated by Django 4.2.5 on 2023-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
