# Generated by Django 5.2.2 on 2025-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryColor',
            field=models.CharField(default='#FFFFFF', max_length=8),
        ),
    ]
